# Beantwortung der Fokusfrage

In diesem Jupyter Notebook wird folgende Fokusfrage beantwortet:

> *An welchem der vier Standorte waren im gesamten April 2024 anteilsmässig die meisten Kinder unterwegs?*

Einerseits werden hier die pandas-Funktionen vorbereitet für die Datenabfrage und andererseits die "spec" für die Darstellung des Diagrammes.

## Vorbereiten der Daten

### Daten aus CSV laden und nach Datumsbereich filtern

In [24]:
import pandas as pd

data = pd.read_csv('../daten/Gesamtdatensatz.csv')
data = data[(data['timestamp'] >= '2024-04-01') & (data['timestamp'] <= '2024-04-30')]
data

,timestamp,location_id,location_name,ltr_label,rtl_label,weather_condition,temperature,pedestrians_count,unverified,collection_type,...,zone_3_pedestrians_count,zone_3_ltr_pedestrians_count,zone_3_rtl_pedestrians_count,zone_3_adult_pedestrians_count,zone_3_child_pedestrians_count,zone_99_pedestrians_count,zone_99_ltr_pedestrians_count,zone_99_rtl_pedestrians_count,zone_99_adult_pedestrians_count,zone_99_child_pedestrians_count
87848,2024-04-01T00:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,11.0,97,False,measured,...,65.0,51.0,14.0,65.0,0.0,NaN,NaN,NaN,NaN,NaN
87849,2024-04-01T00:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,11.0,118,False,measured,...,40.0,12.0,28.0,40.0,0.0,NaN,NaN,NaN,NaN,NaN
87850,2024-04-01T00:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,11.0,32,False,measured,...,22.0,8.0,14.0,21.0,1.0,NaN,NaN,NaN,NaN,NaN
87851,2024-04-01T00:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,11.0,17,False,measured,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87852,2024-04-01T01:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,partly-cloudy-night,10.0,123,False,measured,...,78.0,73.0,5.0,78.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90627,2024-04-29T22:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,clear-night,10.9,6,False,measured,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90628,2024-04-29T23:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,partly-cloudy-night,10.8,15,False,measured,...,3.0,2.0,1.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN
90629,2024-04-29T23:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,partly-cloudy-night,10.8,13,False,measured,...,7.0,0.0,7.0,7.0,0.0,NaN,NaN,NaN,NaN,NaN
90630,2024-04-29T23:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,partly-cloudy-night,10.8,33,False,measured,...,26.0,10.0,16.0,18.0,8.0,NaN,NaN,NaN,NaN,NaN
90631,2024-04-29T23:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,partly-cloudy-night,10.8,2,False,measured,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Gruppieren und summieren der relevanten Spalten nach Standort

In [25]:
data = data.groupby(['location_name'], as_index=False)[[
    'child_pedestrians_count',
    'adult_pedestrians_count',
    'pedestrians_count',
]].sum()
data

,location_name,child_pedestrians_count,adult_pedestrians_count,pedestrians_count
0,Bahnhofstrasse (Mitte),20686,1099830,1120516
1,Bahnhofstrasse (Nord),7070,866905,873975
2,Bahnhofstrasse (Süd),21152,669023,690175
3,Lintheschergasse,3310,313929,317239

### Spalten umbenennen als Vorbereitung für das Diagramm

In [26]:
data = data.rename(columns={
    'location_name': 'Standort',
    'child_pedestrians_count': 'Anzahl Kinder',
    'adult_pedestrians_count': 'Anzahl Erwachsene',
    'pedestrians_count': 'Anzahl Passanten',
})
data

                 Standort  Anzahl Kinder  Anzahl Erwachsene  Anzahl Passanten
0  Bahnhofstrasse (Mitte)          20686            1099830           1120516
1   Bahnhofstrasse (Nord)           7070             866905            873975
2    Bahnhofstrasse (Süd)          21152             669023            690175
3        Lintheschergasse           3310             313929            317239

### Anteil Kinder in % pro Standort berechnen

In [27]:
data['Anteil Kinder'] = data['Anzahl Kinder'] / data['Anzahl Passanten']
data

,Standort,Anzahl Kinder,Anzahl Erwachsene,Anzahl Passanten,Anteil Kinder
0,Bahnhofstrasse (Mitte),20686,1099830,1120516,0.018461
1,Bahnhofstrasse (Nord),7070,866905,873975,0.008089
2,Bahnhofstrasse (Süd),21152,669023,690175,0.030647
3,Lintheschergasse,3310,313929,317239,0.010434

### NaN-Werte in Spalte 'Anteil Kinder' durch 0 ersetzen
NaN-Werte können bei der Division durch 0 entstehen, wenn die Anzahl Passanten 0 ist.

In [28]:
data['Anzahl Kinder'] = data['Anzahl Kinder'].fillna(0)
data

,Standort,Anzahl Kinder,Anzahl Erwachsene,Anzahl Passanten,Anteil Kinder
0,Bahnhofstrasse (Mitte),20686,1099830,1120516,0.018461
1,Bahnhofstrasse (Nord),7070,866905,873975,0.008089
2,Bahnhofstrasse (Süd),21152,669023,690175,0.030647
3,Lintheschergasse,3310,313929,317239,0.010434

### Spalte mit höchstem Kinderanteil markieren

In [29]:
max_anteil = data['Anteil Kinder'].max()
data['Höchster'] = data['Anteil Kinder'] == max_anteil
data

,Standort,Anzahl Kinder,Anzahl Erwachsene,Anzahl Passanten,Anteil Kinder,Höchster
0,Bahnhofstrasse (Mitte),20686,1099830,1120516,0.018461,False
1,Bahnhofstrasse (Nord),7070,866905,873975,0.008089,False
2,Bahnhofstrasse (Süd),21152,669023,690175,0.030647,True
3,Lintheschergasse,3310,313929,317239,0.010434,False

## Definition des Diagrammes

In [30]:
import altair as alt

bar_width = 80
bar_spacing = 0.4 * bar_width
chart_height = 400

chart = alt.Chart(data).mark_bar(size=bar_width).encode(
    x=alt.X(
        'Standort:N',
        sort=['Bahnhofstrasse (Nord)', 'Bahnhofstrasse (Mitte)', 'Bahnhofstrasse (Süd)', 'Lintheschergasse'],
    ).axis(
        labelAngle=-45,
        labelOffset=bar_width / 4,
    ), 
    y=alt.Y('Anteil Kinder:Q').axis(
        format='.1%',
        tickCount=7,
    ),
    color=alt.condition(
        'datum.Höchster',
        alt.value('purple'),
        alt.value('steelblue')
    ),
    tooltip=[
        alt.Tooltip('Anteil Kinder', format='.1%'),
        alt.Tooltip('Anzahl Kinder', format=','),
        alt.Tooltip('Anzahl Erwachsene', format=','),
        alt.Tooltip('Anzahl Passanten', format=','),
    ],
).properties(
    width={'step': bar_width + bar_spacing},
    height=chart_height
).configure_axis(
    titleFontSize=17, 
    labelFontSize=15,
)
chart

alt.Chart(...)

## Generieren der Spec für die Darstellung des Diagrammes

In [31]:
import json

# In Dictionary umwandeln
spec = chart.to_dict()

# Dataset umbenennen in "values" für einfacheren Zugriff im Frontend
new_name = 'values'
old_name = spec['data']['name']
spec['data']['name'] = new_name
spec['datasets'][new_name] = spec['datasets'].pop(old_name)

# Spec in eine Datei schreiben
with open('fokusfrage.json', 'w') as f:
    json.dump(spec, f, indent=2)